{
 "title": "SMA Smart Energy 10.0",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "kWEuroEinspeisung", "label": "€/kWh Einspeisung", "query": "0.1095" },
   { "name": "kWEuroBezug", "label": "€/kWh Netzbezug", "query": "0.2775" }
  ]
 },
 "panels": [
  {
   "title": "Energiefluss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"meterInW\" or r[\"_field\"] == \"meterOutW\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({_value: r.meterInW - r.meterOutW,_time: r._time, _field:\"Energiefluss\"}))\r\n  |> last()",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Erzeugung",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"generatorW\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "Total DC power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"batdischargeW\" or r[\"_field\"] == \"batchargeW\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({_value: r.batdischargeW -r.batchargeW,_time: r._time, _field:\"Batterieladung\"}))\r\n  |> last()",
     "select": [
      [
       {
        "params": [
         "Current battery charge-discharge power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbrauch",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Westen / hinten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"consumptW\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "Total AC active power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Erzeugung",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Westen / hinten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"generatorW\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "Power DC1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Batterie Ladezustand",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"batSOC\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "Battery current SOC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"PV-Anlage\")\r\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"generatedWh\" or r[\"_field\"] == \"exportedWh\"  or r[\"_field\"] == \"importedWh\" or r[\"_field\"] == \"batchargeWh\" or r[\"_field\"] == \"batdischargeWh\")\r\n  |> difference()\r\n  |> sum()\r\n  |> pivot(rowKey: [\"_start\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with PV: (r.generatedWh -r.exportedWh - r.batchargeWh ) / \r\n           (r.generatedWh -r.exportedWh + r.importedWh - r.batchargeWh + r.batdischargeWh)}))\r\n  |> keep(columns: [\"PV\"])\r\n // |> yield(name: \"PV\")"
    },
    {
     "query": "from(bucket: \"PV-Anlage\")\r\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"generatedWh\" or r[\"_field\"] == \"exportedWh\"  or r[\"_field\"] == \"importedWh\" or r[\"_field\"] == \"batchargeWh\" or r[\"_field\"] == \"batdischargeWh\")\r\n  |> difference()\r\n  |> sum()\r\n  |> pivot(rowKey: [\"_start\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with Batterie: r.batdischargeWh  / \r\n           (r.generatedWh -r.exportedWh + r.importedWh - r.batchargeWh + r.batdischargeWh)}))\r\n  |> keep(columns: [\"Batterie\"])\r\n  |> yield(name: \"Batterie\")"
    },
    {
     "query": "from(bucket: \"PV-Anlage\")\r\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> range(start: today())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"generatedWh\" or r[\"_field\"] == \"exportedWh\"  or r[\"_field\"] == \"importedWh\" or r[\"_field\"] == \"batchargeWh\" or r[\"_field\"] == \"batdischargeWh\")\r\n  |> difference()\r\n  |> sum()\r\n  |> pivot(rowKey: [\"_start\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with Netz: r.importedWh  / \r\n           (r.generatedWh -r.exportedWh + r.importedWh - r.batchargeWh + r.batdischargeWh)}))\r\n  |> keep(columns: [\"Netz\"])\r\n  |> yield(name: \"Netz\")"
    }
   ]
  },
  {
   "title": "Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "String 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pv-stats\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"powerA\" or r[\"_field\"] == \"powerB\") \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Power DC1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pv-stats\")\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"powerB\" or r[\"_field\"] == \"powerA\") \r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: r.powerA + r.powerB, _time: r._time}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"_value\"])\r\n  |> rename(columns: {_value: \"Power Ost + Süd\"})\r\n  |> yield(name: \"mean\")"
    },
    { "target": [ "sun_altitude" ] }
   ]
  },
  {
   "title": "Hausverbrauch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Batterie laden",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"meterInW\" or r[\"_field\"] == \"meterOutW\" \r\n       or r[\"_field\"] == \"batchargeW\" or r[\"_field\"] == \"batdischargeW\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "Current battery charge-discharge power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "Current battery charge-discharge power",
       "operator": "<",
       "value": "0"
      }
     ]
    },
    {
     "alias": "Batterie entladen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"power-stats\" )\r\n  |> filter(fn: (r) =>   r[\"_field\"] == \"generatorW\" or r[\"_field\"] == \"meterOutW\" or r[\"_field\"] == \"batchargeW\" )\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({ _value: (r.generatorW - r.meterOutW -r.batchargeW) , _time: r._time, _field: \"direktverbrauch\"})) \r\n  |> aggregateWindow(every: v.windowPeriod, fn: first, createEmpty: false)\r\n  |> keep(columns: [\"_time\",\"_value\"] )\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "Home own consumption from battery"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbrauch nach Erzeuger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"generatorW\" or r[\"_field\"] == \"meterOutW\" or r[\"_field\"] == \"batchargeW\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({_value: r.generatorW -r.meterOutW -r.batchargeW,_time: r._time, _field: \"PV\"})) \r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"meterInW\"  or r[\"_field\"] == \"batdischargeW\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Total AC active power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC/AC Wirkungsgrad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "powerDC =\r\nfrom(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"pv-stats\" )\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"powerA\" or r[\"_field\"] == \"powerB\" )\r\n  |> map(fn: (r) => ({ r with _measurement:\"power-stats\"}))\r\n\r\npowerAC = \r\nfrom(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"power-stats\" )\r\n  |> filter(fn: (r) =>  r[\"_field\"] == \"generatorW\" )\r\nunion(tables: [powerDC, powerAC])\r\n|> aggregateWindow(every: v.windowPeriod, fn: first, createEmpty: false)\r\n|> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n|> map(fn: (r) => ({r with efficiency: if  r.generatorW > (r.powerA + r.powerB)  then 97.0 else r.generatorW / (r.powerA + r.powerB) * 100.0 , _time: r._time, _field: \"efficiency\"})) \r\n|> keep(columns: [\"_time\",\"efficiency\"] )"
    }
   ]
  },
  {
   "title": "Batterie Ladeleistung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Laden",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"power-stats\" )\r\n  |> filter(fn: (r) =>   r[\"_field\"] == \"batchargeW\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first, createEmpty: false)\r\n  //|> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "Current battery charge-discharge power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "Current battery charge-discharge power",
       "operator": "<",
       "value": "0"
      }
     ]
    },
    {
     "alias": "Entladen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"power-stats\" )\r\n  |> filter(fn: (r) =>   r[\"_field\"] == \"batdischargeW\" )\r\n  |> map(fn: (r) => ({r with _value: r._value * -1.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first, createEmpty: false)\r\n  //|> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "Current battery charge-discharge power"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "Current battery charge-discharge power",
       "operator": ">",
       "value": "0"
      }
     ]
    }
   ]
  },
  {
   "title": "Netz Einspeisung/Bezug",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Einspeisung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"power-stats\" )\r\n  |> filter(fn: (r) =>   r[\"_field\"] == \"meterOutW\" )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n  ",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "Total active power (powermeter)",
       "operator": "<",
       "value": "0"
      }
     ]
    },
    {
     "alias": "Bezug",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>  r[\"_measurement\"] == \"power-stats\" )\r\n  |> filter(fn: (r) =>   r[\"_field\"] == \"meterInW\" )\r\n  |> map(fn: (r) => ({r with _value: r._value * -1.0}))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: first, createEmpty: false)\r\n//|> yield(name: \"mean\")",
     "select": [
      [
       {
        "params": [
         "Total active power (powermeter)"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "Total active power (powermeter)",
       "operator": ">",
       "value": "0"
      }
     ]
    }
   ]
  },
  {
   "title": "Batterie Ladezustand",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Ladezustand",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "from(bucket: \"PV-Anlage\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"power-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"batSOC\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "Battery current SOC" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Einspeisung/Bezug pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\n\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\n\r\ndata = from(bucket: \"PV-Anlage\")\r\n  |> range(start: date.add(d: -7d, to: today()), stop: date.truncate(t: today(), unit: 1d))\r\n  |> filter(fn: (r) => r._measurement == \"energy-stats\")\r\n  |> filter(fn: (r) => r._field == \"exportedWh\"  or r._field == \"importedWh\")\r\n  |> difference()\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true, timeSrc: \"_start\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\"])\r\n\r\nexportedWh = data |> map(fn: (r) => ({ _value: r.exportedWh, _time: r._time, _field: \"exportedWh\" }))\r\nimportedWh = data |> map(fn: (r) => ({ _value: - r.importedWh, _time: r._time, _field: \"importedWh\" }))\r\n\r\n\r\nunion(tables: [exportedWh, importedWh])\r\n  |> group(columns:[\"_field\"])"
    }
   ]
  },
  {
   "title": "Kosten/Einnahmen pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"date\"\r\n\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nfrom(bucket: \"PV-Anlage\")\r\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> range(start: date.add(d: -7d, to: today()), stop: date.truncate(t: today(), unit: 1d))\r\n  //|> range(start: -7d, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"generatedWh\" or r[\"_field\"] == \"exportedWh\" or r[\"_field\"] == \"batchargeWh\" \r\n     or r[\"_field\"] == \"batdischargeWh\" or r[\"_field\"] == \"exportedWh\" or  r[\"_field\"] == \"priceIn\" or  r[\"_field\"] == \"priceOut\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with _value: (r.generatedWh -r.exportedWh -r.batchargeWh + r.batdischargeWh) / 1000. * r.priceIn + r.exportedWh/1000.0 * r.priceOut}))\r\n  |> keep(columns: [\"_value\",\"_time\"])\r\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: true)\r\n  // |> aggregateWindow(every: 1d, fn: spread, createEmpty: false)\r\n  //|> aggregateWindow(every: 1w, offset: -3d, fn: sum)\r\n |> difference() \r\n\r\n \r\n  "
    },
    {
     "query": "\r\nimport \"timezone\"\r\nimport \"date\"\r\n\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nfrom(bucket: \"PV-Anlage\")\r\n  //|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n // |> range(start: -7d, stop: now())\r\n |> range(start: date.add(d: -7d, to: today()), stop: date.truncate(t: today(), unit: 1d))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"importedWh\"  or  r[\"_field\"] == \"priceIn\")\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({r with Kosten: (r.importedWh) / 1000. * - r.priceIn}))\r\n  |> keep(columns: [\"Kosten\",\"_time\"])\r\n  |> aggregateWindow(every: 1d, fn: last, createEmpty: true, column: \"Kosten\")\r\n  |> difference(columns: [\"Kosten\"]) \r\n  //|> keep(columns: [\"Kosten\"])"
    }
   ]
  },
  {
   "title": "Tägliche Erzeugung",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Daily yield",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "modbus.HoldingRegister",
     "query": "import \"timezone\"\r\nimport \"date\"\r\noption location = timezone.location(name: \"Europe/Berlin\")\r\nfrom(bucket: \"PV-Anlage\")\r\n  |> range(start: date.add(d: -7d, to: today()), stop: date.truncate(t: today(), unit:1d))\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"energy-stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"generatedWh\" )\r\n  |> difference()\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: true, timeSrc: \"_start\")\r\n  |> drop(columns: [\"_start\",\"_stop\",\"_measurement\"])\r\n  ",
     "select": [
      [
       { "params": [ "Daily yield" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}